//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string emp_usr { get; set; }
        public string emp_pwd { get; set; }
        public string emp_name { get; set; }
        public string emp_phone { get; set; }
        public string emp_address { get; set; }
        public int emp_role { get; set; }
    }
}
