//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVALUATE
    {
        public int eva_id { get; set; }
        public string cus_usr { get; set; }
        public Nullable<int> book_id { get; set; }
        public System.DateTime eva_date { get; set; }
        public string eva_title { get; set; }
        public string eva_content { get; set; }
        public int eva_rate { get; set; }
        public string eva_imgs { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
