//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiki
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public int ord_id { get; set; }
        public int book_id { get; set; }
        public int ord_quantity { get; set; }
        public int ord_price { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
